apiVersion: v2
name: github-slack-bridge
description: GitHub Slack Bridge Helm Chart
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: common
    version: 1.20.0
    repository: "https://entur.github.io/helm-charts"
