common:
  app: github-slack-bridge
  shortname: gthbslckbr # Defined in https://github.com/entur/ror-tf-gcp-common-infrastructure/blob/main/.entur/github-slack-bridge/app-gsb.yml
  team: team-ror
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 8080  # What TCP port the application listens on the pod, must match the port in the Dockerfile
  deployment:
    prometheus:
      enabled: false  # Set this to true only after you have setup a metrics endpoint
  container:
    image: <+artifacts.primary.image>  # The CD tool will replace this value with the actual image
    cpu: 0.3 # Adjust this to your application needs
    memory: 512 # Adjust this to your application needs, a java application might need more memory to start like 1024 or 2048 or +++
  postgres: # sets up a postgres proxy so you can connect to your postgresql instance via localhost on the pod
    enabled: true
    cpu: 0.1  # PostgreSQL Proxy setting, this usually is enough for most applications
    memory: 32  # PostgreSQL Proxy setting, this usually is enough for most applications
  secrets:
    app-secrets:
      - GITHUB_WEBHOOK_SECRET
      - SLACK_WEBHOOK_URL
