name: Build it

on:
  push:
  pull_request:

jobs:
  lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile

  build:
    needs: lint
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      dockerfile: Dockerfile
      image_name: github-slack-bridge

  push:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      dockerfile: Dockerfile
      image_name: github-slack-bridge

  scan:
    needs: [build]
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.build.outputs.image_artifact }}

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: push
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: ${{ needs.push.outputs.image_name }}:${{ needs.push.outputs.image_tag}}
      chart: helm/github-slack-bridge
      namespace: github-slack-bridge
      release_name: github-slack-bridge
    secrets: inherit
